### ISSUE TITLE
Aurelia Docs

### ISSUE THREAD

**Issue by EisenbergEffect** [gordon-matt/aurelia-razor-skeleton#1]
@gordon-matt I finally got to read the article you sent me. I think this could be broadly useful information. Would you be interested in slightly working your article? We have a section of our documentation dedicated to integrating with other technology. I think this would be a great topic for that. Basically, some slight re-work to make the article fit into a documentation context, along with the content being written in markdown would be all that's needed. You would receive full attribution within our docs of course. Let me know what you think.

**Comment by gordon-matt** [comment]
Hi Rob. My apologies for the late response. I have been inundated with work as of late. I am sure you know what that's like. Regarding the article; as previously stated, I am not much of a writer. However, I will see what I can do about improving on what I've already sent you. What do you think might be missing? It might help me finish this faster if you could elaborate on what you mean by "re-work" it slightly.

**Comment by EisenbergEffect** [comment]
The first thing would be to write the content using markdown. After that, it just might need some re-wording so that it makes sense from the perspective of someone searching and finding it in the docs and wanted to read a how-to.

**Comment by gordon-matt** [comment]
Closing this issue, as I have not been able to look at Aurelia again until now and have found that there is now a much better example, with a tutorial written by someone named Dan Pettersson. The tutorial can be found here: [Converting the ASP.NET Core MVC template to an Aurelia SPA – keeping the Razor views](http://blog.deap.nu/2017/05/06/converting-the-asp-net-core-mvc-template-to-an-aurelia-spa-keeping-the-razor-views/)

**Comment by gordon-matt** [comment]
@EisenbergEffect You may be interested in my new skeleton project:
https://github.com/gordon-matt/aurelia-razor-netcore2-skeleton

It targets .NET Core 2.0 and has Razor views and dynamic routes working quite well. I am still learning Aurelia, but I think I've made a good start and this skeleton project (which also includes both the Todo list and Contact Manager tutorials) may be of interest to some others, as I have seen quite a few people have tried getting Razor views working for Aurelia, but I've yet to find someone with the same solution I have. A few days ago I thought I did find a satisfactory solution with the link I shared in my previous message above, but I was wrong.

Also FYI - I will be releasing my custom CMS as open source once it's stable (migrating it from MVC5 to .NET Core at the moment) and it's currently using Durandal but I will be moving to Aurelia at some point. Depending on the amount of work needed to move to Aurelia, I may release the CMS before doing that... in any case, I'll let you know when that happens if you like...

**Comment by EisenbergEffect** [comment]
@gordon-matt Sounds great! Would you be interested at all in guest blogging on the official Aurelia blog to talk about the template and how you combined Aurelia and ASP.NET Core 2? I'm sure the community would be interested.

**Comment by gordon-matt** [comment]
@EisenbergEffect I'd be happy to. Are there any guidelines or formatting that I need to adhere to for the Aurelia blog?

By the way, I just got on your "Aurelia Discourse" a couple of days ago to ask a question. When I replied to myself I got a message saying that a moderator needs to review it (because I am a new user, I guess). I'm still waiting. I assume you don't have many moderators and/or they are too busy at the moment. Would appreciate if someone could please allow me to post questions and replies.

I'll start working on the blog article soon.

**Comment by EisenbergEffect** [comment]
For some reason Discourse doesn't alert me when there's something I need to moderate. I've gone ahead and approved that for you. Sorry for the delay!

For the blog, if you just want to put together something using Markdown as a start, that would be great. I can work with you to refine it once you've got a first draft.

**Comment by gordon-matt** [comment]
@EisenbergEffect No worries, Rob! I think I still have your email address and I will post my draft there when ready. It shouldn't take me too long.

**Comment by gordon-matt** [comment]
@EisenbergEffect I have just sent the draft to your Blue Spire email address. Take your time - no rush.
